# Generated by Django 4.2.4 on 2025-12-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enrollment",
            old_name="Course",
            new_name="course",
        ),
        migrations.RenameField(
            model_name="enrollment",
            old_name="data_enrolled",
            new_name="date_enrolled",
        ),
        migrations.RemoveField(
            model_name="user",
            name="fist_name",
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="john", max_length=30),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(default="online course", max_length=100),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(default="title", max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="doe", max_length=30),
        ),
    ]
