# Generated by Django 5.2.8 on 2025-12-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer360", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="social_media",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="channel",
            field=models.CharField(
                choices=[
                    ("phone", "Telefon"),
                    ("sms", "SMS"),
                    ("email", "E-posta"),
                    ("letter", "Mektup"),
                    ("social_media", "Sosyal Medya"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="direction",
            field=models.CharField(
                choices=[("inbound", "Gelen"), ("outbound", "Giden")], max_length=12
            ),
        ),
    ]
