# Generated by Django 5.2.9 on 2025-12-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Kitap Adı")),
                ("author", models.CharField(max_length=150, verbose_name="Yazar")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "published_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Yayın Tarihi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
            ],
        ),
    ]
